"""Initial private portfolio schema"""

from alembic import op
import sqlalchemy as sa

revision = "ccec6252b6b9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("asset_type", sa.String(length=30), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=False),
        sa.Column("industry", sa.String(length=160), nullable=True),
        sa.Column("public", sa.Boolean(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol"),
    )
    op.create_table(
        "historical_prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=100), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("close", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("adjusted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "date", "provider"),
    )
    with op.batch_alter_table("historical_prices", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_historical_prices_date"), ["date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_historical_prices_symbol"), ["symbol"], unique=False
        )

    op.create_table(
        "job_leases",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_login_attempts_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_login_attempts_key"), ["key"], unique=False
        )

    op.create_table(
        "market_cache",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name"),
    )
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_accounts_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=100), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("source_key", sa.String(length=160), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "source_key"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_date"), ["date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_events_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "scenarios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("shocks", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scenarios", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scenarios_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("csrf", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sessions_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "key"),
    )
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_settings_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_value", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("cash", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("cost_basis", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("contributions", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("external_flow", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("positions", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", "source"),
    )
    with op.batch_alter_table("snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_snapshots_date"), ["date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_snapshots_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "sync_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("diagnostics", sa.JSON(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sync_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sync_runs_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "theses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=100), nullable=False),
        sa.Column("thesis", sa.Text(), nullable=False),
        sa.Column("risks", sa.Text(), nullable=False),
        sa.Column("catalysts", sa.Text(), nullable=False),
        sa.Column("conviction", sa.Integer(), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "symbol"),
    )
    with op.batch_alter_table("theses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_theses_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "watchlists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name"),
    )
    with op.batch_alter_table("watchlists", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_watchlists_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "holdings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("price", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("cost_basis", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("value", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("daily_change", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("daily_date", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("cost_basis >= 0"),
        sa.CheckConstraint("value >= 0"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "asset_id"),
    )
    with op.batch_alter_table("holdings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_holdings_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_holdings_asset_id"), ["asset_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_holdings_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("symbol", sa.String(length=100), nullable=True),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("date_label", sa.String(length=80), nullable=True),
        sa.Column("amount", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("realized_gain", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("source_key", sa.String(length=160), nullable=False),
        sa.CheckConstraint("amount >= 0"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "source_key"),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transactions_date"), ["date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transactions_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "watch_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("watchlist_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=100), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("conviction", sa.Integer(), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("alert_below", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("alert_above", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.CheckConstraint("conviction >= 1 AND conviction <= 5"),
        sa.ForeignKeyConstraint(
            ["watchlist_id"], ["watchlists.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("watchlist_id", "symbol"),
    )
    with op.batch_alter_table("watch_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_watch_items_watchlist_id"), ["watchlist_id"], unique=False
        )

    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=100), nullable=True),
        sa.Column("transaction_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("source_key", sa.String(length=160), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"], ["transactions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "source_key"),
    )
    with op.batch_alter_table("journal_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_journal_entries_date"), ["date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_journal_entries_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("journal_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_journal_entries_user_id"))
        batch_op.drop_index(batch_op.f("ix_journal_entries_date"))

    op.drop_table("journal_entries")
    with op.batch_alter_table("watch_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watch_items_watchlist_id"))

    op.drop_table("watch_items")
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transactions_user_id"))
        batch_op.drop_index(batch_op.f("ix_transactions_date"))

    op.drop_table("transactions")
    with op.batch_alter_table("holdings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_holdings_user_id"))
        batch_op.drop_index(batch_op.f("ix_holdings_asset_id"))
        batch_op.drop_index(batch_op.f("ix_holdings_account_id"))

    op.drop_table("holdings")
    with op.batch_alter_table("watchlists", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watchlists_user_id"))

    op.drop_table("watchlists")
    with op.batch_alter_table("theses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_theses_user_id"))

    op.drop_table("theses")
    with op.batch_alter_table("sync_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_runs_user_id"))

    op.drop_table("sync_runs")
    with op.batch_alter_table("snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_snapshots_user_id"))
        batch_op.drop_index(batch_op.f("ix_snapshots_date"))

    op.drop_table("snapshots")
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_settings_user_id"))

    op.drop_table("settings")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_expires_at"))

    op.drop_table("sessions")
    with op.batch_alter_table("scenarios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scenarios_user_id"))

    op.drop_table("scenarios")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_user_id"))
        batch_op.drop_index(batch_op.f("ix_events_date"))

    op.drop_table("events")
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_user_id"))

    op.drop_table("accounts")
    op.drop_table("users")
    op.drop_table("market_cache")
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_login_attempts_key"))
        batch_op.drop_index(batch_op.f("ix_login_attempts_created_at"))

    op.drop_table("login_attempts")
    op.drop_table("job_leases")
    with op.batch_alter_table("historical_prices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_historical_prices_symbol"))
        batch_op.drop_index(batch_op.f("ix_historical_prices_date"))

    op.drop_table("historical_prices")
    op.drop_table("assets")
    # ### end Alembic commands ###
